<?php
/**
 * Created by PhpStorm.
 * User: Red-Bo
 * Date: 2016/5/26
 * Time: 23:30
 */

/**
 * 装饰起模式
 */

/**
 * 组件对象接口
 * Interface IComponent
 */
interface IComponent
{
    function Display();
}

/**
 * 待装饰对象
 * Class Person
 */
class Person implements IComponent
{
    private $name;

    function __construct($name)
    {
        $this->name = $name;
    }

    function Display()
    {
       echo "装扮的：{$this->name}<br/>";
    }
}

class Clothers implements IComponent
{
    protected $component;

    function Decorate(IComponent $component)
    {
        $this->component = $component;
    }

    function Display()
    {
        if(!empty($this->component))
        {
            $this->component->Display();
        }
    }
}


// ------------------ 具体装饰器-----------

class Pixie extends Clothers
{
    function Display()
    {
        echo "皮鞋  ";
        parent::Display(); // TODO: Change the autogenerated stub
    }
}

class Qiuxie extends Clothers
{
    function Display()
    {
        echo "球鞋  ";
        parent::Display(); // TODO: Change the autogenerated stub
    }
}

class Tshirt extends Clothers
{
    function Display()
    {
        echo "T桖  ";
        parent::Display(); // TODO: Change the autogenerated stub
    }
}

class Waitao extends Clothers
{
    function Display()
    {
        echo "外套 ";
        parent::Display(); // TODO: Change the autogenerated stub
    }
}
